"""The HID report descriptor, verified three ways:

  1. what the library generated        -- `RMAP?` (getHidReportDescriptor())
  2. what the library says its size is  -- `RSIZE?` (getHidReportDescriptorSize())
  3. what the kernel actually received  -- /sys/class/hidraw/.../report_descriptor
  4. what we expect it to be            -- firmware/golden/<profile>.hiddesc

(1) == (3) proves the descriptor survived BLE transport intact (no truncation,
no buffer overrun). (1) == (4) catches library descriptor-generation
regressions -- regenerate the golden with `pytest --update-golden` after an
intentional change.
"""

import pathlib

import pytest

from hil import hidraw

REPO = pathlib.Path(__file__).resolve().parents[2]
GOLDEN_DIR = REPO / "firmware" / "golden"


def _diff(want, got):
    wi, gi = hidraw.decode_items(want), hidraw.decode_items(got)
    lines = [f"descriptor differs: {len(want)}B expected vs {len(got)}B got"]
    for n, (a, b) in enumerate(zip(wi, gi)):
        if a != b:
            lines.append(f"  item {n}: {a[0]}={a[1]}  ->  {b[0]}={b[1]}")
    if len(wi) != len(gi):
        lines.append(f"  item count {len(wi)} -> {len(gi)}")
    return "\n".join(lines)


@pytest.fixture(scope="module")
def descriptors(connected_dut, bt_mac):
    """(library-generated bytes, kernel-received bytes, hidraw node)."""
    fw = connected_dut.report_descriptor()  # RMAP? -- serial, not BLE
    node = hidraw.find_node()
    kern = hidraw.descriptor_via_sysfs(node) if node else None
    return fw, kern, node


def test_library_size_matches_bytes(connected_dut, descriptors):
    fw, _, _ = descriptors
    assert len(fw) == connected_dut.report_sizes()["descriptor"]
    assert len(fw) <= 150  # tempHidReportDescriptor[150]


def test_kernel_received_intact(descriptors):
    fw, kern, node = descriptors
    assert node, "no /dev/hidraw node found for the DUT"
    assert kern == fw, _diff(fw, kern)


def test_matches_golden(descriptors, rigcfg, pytestconfig):
    fw, _, _ = descriptors
    golden = GOLDEN_DIR / f"{rigcfg['profile']}.hiddesc"
    if pytestconfig.getoption("update_golden"):
        GOLDEN_DIR.mkdir(parents=True, exist_ok=True)
        golden.write_text(fw.hex() + "\n")
        pytest.skip(f"golden updated: {golden.name} ({len(fw)} B)")
    if not golden.exists():
        pytest.skip(
            f"no golden for profile {rigcfg['profile']!r} yet -- "
            f"run once with --update-golden and commit "
            f"firmware/golden/{rigcfg['profile']}.hiddesc"
        )
    want = bytes.fromhex(golden.read_text().strip())
    assert fw == want, _diff(want, fw)
